inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'cache/**/*'
    - '.bundle/**/*'
    - 'db/*'
    - 'db/seeds/*'
    - 'bin/*'
    - 'log/**/*'

RSpec/ContextWording:
  Enabled: false

RSpec/NestedGroups:
  Max: 4
