Style/ClassAndModuleChildren:
  Enabled: false
Metrics/LineLength:
  Max: 80
Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
